### ISSUE TITLE
Load Comments no working

### ISSUE THREAD

**Issue by DmytroCrawford** [gurbaaz27/linkedin-comments-scraper#5]
I've been trying to fix the utilities.py file so that the load comments function works, but I am struggling to make it work. Linkedin has changed its "load more comments" button since the code was first written but was wondering if I could get some suggestions on how to approach or fix this issue.

**Comment by gurbaaz27** [comment]
Hi! The issue was simply due to the reason same as that of your earlier PR. In function `load_more_comments` in `utilities.py`, the method to find button class being used was `find_element_by_class_name`, which should have been changed to `find_element(By.CLASS_NAME, ...)`. I was simply able to find this reason by printing the Exception in the function to see what is causing the script to not load additional comments.

Anyways, I have made the required changes, and pushed the latest code to the master branch. Pull it locally, test and confirm if it works.

Peace!
